export const API_URL = {
  LOGIN: '/api/auth/login',
  LOGOUT: '/api/auth/logout',
  REGISTER: '/api/auth/register',
  PROFILE: '/api/auth/profile',
  CATEGORY_LIST: '/api/category/list',
  CATEGORY_READ: '/api/category/read',
  PRODUCT_LIST: '/api/product/list',
  PRODUCT_COLORS: '/api/product/listColor',
  PRODUCT_READ: '/api/product/read',
  PRODUCT_COMMENTS: '/api/product/comments',
  PRODUCT_HINT: '/api/product/hint',
  PROVINCE: '/api/location/province',
  CREATE_BILL: '/api/bill/create',
  PUSH_CART: '/api/users/pushCart',
  USER_BILL_LIST: '/api/users/bills',
  BILL_LIST: '/api/bill/list',
  BILL_READ: '/api/bill/read',
  BILL_UPDATE: '/api/bill/update',
  TOP_PRODUCT: '/api/product/top',
  DISTRICT: (proCode: string) => `/api/location/district/${proCode}`,
  WARD: (disCode: string) => `/api/location/ward/${disCode}`,
};
